(** * Anti-spoofing: a proven security property of optiplex.nft's bridge filter.

    [../../rulesets/optiplex.nft] is a real, in-use IPv4/IPv6 firewall.  Its `bridge
    vmfilter` table binds each container's IP to the bridge port it lives behind,
    via two declared sets and, in the bridge `output` chain (policy accept):

      meta obrname br.20 ip daddr @vmaddrs ip daddr . oifname != @vmantispoof drop

    Operationally: for a frame leaving bridge port br.20 whose destination is a
    known VM address (`ip daddr @vmaddrs`) but whose (destination, output-iface)
    pair is NOT the bound pair (`ip daddr . oifname != @vmantispoof`), DROP.  This
    stops one container impersonating another's IP: traffic to a VM's address may
    only ever exit that VM's own veth.

    Crucially, we do NOT hand-translate the ruleset here.  [Optiplex_Gen.v] is the
    Menhir frontend's OUTPUT: the parser (extracted/nft_*.ml) reads
    ../../rulesets/optiplex.nft and emits the chains ([vmfilter_output], ...) and the
    set/map declarations ([decls]/[gen_env]) as the Coq terms below.  So the chain
    these theorems are about IS the parser's output — there is no eyeballed step
    between the `.nft` text and the theorem.  Via [compile_table_correct] every
    property transports to the installed netlink bytecode.

    NOTE on [Optiplex_Gen.filter_chains]: optiplex.nft also declares an inet
    `filter` table, which the parser faithfully emits as [filter_chains].  These
    anti-spoofing theorems only reason about the bridge `vmfilter` table
    ([vmfilter_chains]), so [filter_chains] is parsed-but-unproved.  It is NOT
    dead code to strip: [Optiplex_Gen.v] is auto-generated by `make gen`
    (nft2coq) and deleting [filter_chains] by hand would diverge the committed
    file from the regenerated parser output and silently drop a faithful parse of
    a real table. *)

From Stdlib Require Import List String Ascii NArith.
From Nft Require Import Bytes Verdict Packet Syntax Semantics Optiplex_Gen Nftval.
Import ListNotations.
Open Scope string_scope.

(** ** Wire-value notation, only to *state* the hypotheses about a packet.
    These do not define the ruleset (that comes from [Optiplex_Gen]); they only
    name the bytes a given packet's fields hold.  Both are now the register bytes
    of the CENTRAL typed nft values defined in [Nftval.v] (with validity
    predicates [ipv4_valid] / [ifname_valid] and byte-witnesses): [ip4 a b c d]
    is [encode (Nftval.ip4 a b c d)] and [ifreg s] is [encode (Nftval.ifname s)]
    — the IFNAMSIZ-padded 16-byte register the kernel compares.  Each reduces to
    the same bytes the [vm_compute] proofs use; the [*_typed] lemmas pin it. *)
Definition ip4 (a b c d : nat) : data := encode (Nftval.ip4 a b c d).

(* An interface-name register is a fixed 16-byte (IFNAMSIZ) zero-padded buffer;
   the kernel compares the full 16 bytes for an exact name match. *)
Definition ifreg (s : string) : data := encode (Nftval.ifname s).

Lemma ip4_typed : forall a b c d, ip4 a b c d = encode (Nftval.ip4 a b c d).
Proof. reflexivity. Qed.
Lemma ifreg_typed : forall s, ifreg s = encode (Nftval.ifname s).
Proof. reflexivity. Qed.

(* the field a `meta obrname` match reads (output bridge-port name) *)
Definition Fobrname : field := FMetaGen MKbri_oifname.

(* the output chain takes no jumps; fuel need only cover its two rules *)
Definition vm_fuel : nat := 4.

(** ** Stepping lemmas for the fuel-bounded interpreter. *)
Lemma erj_drop_first : forall f cs r rest e p,
  rule_loadable r e p = true -> rule_applies r e p = true -> outcome r e p = Some Drop ->
  eval_rules_j (S f) cs (r :: rest) e p = Some Drop.
Proof. intros f cs r rest e p Hld Hap Hout. cbn. rewrite Hld, Hap, Hout. reflexivity. Qed.

Lemma erj_skip : forall f cs r rest e p,
  rule_applies r e p = false ->
  eval_rules_j (S f) cs (r :: rest) e p = eval_rules_j f cs rest e p.
Proof. intros f cs r rest e p Hap. cbn. rewrite Hap, Bool.andb_false_r. reflexivity. Qed.

(** ** The general anti-spoofing theorem (about the PARSED chain [vmfilter_output]).

    For ANY frame leaving bridge port br.20 whose destination is a protected VM
    address but whose (destination, output-interface) pair is not the bound pair,
    the parsed ruleset's verdict is [Drop] — stated directly in terms of the two
    set memberships, so it holds for every such address/interface.

    M4 NOTE — no whole-env pin.  This headline quantifies over the ENTIRE env:
    the chain's only shared-state reads are the two set memberships, and those
    are already the theorem's own hypotheses (over [e_set e], not [e_set
    gen_env]), so pinning [e = gen_env] — as the pre-M4 statement did — added
    NOTHING except a latent trap: had the chain ever grown an env-reading
    match (ct/fib/rt/numgen), the pin would have silently narrowed "for all
    frames" to the parser's empty world (empty conntrack, no routes) — exactly
    the vacuity that bit Optiplex_Mark ([genenv_fib_local_contradiction]) and
    the Router ct theorems ([Router_Realistic.ctstate_under_genenv_never_new]).
    Machine-checked evidence the pin was inert: this proof is the pre-M4 proof
    with the [?Henv] rewrite deleted and nothing else changed.  The pinned
    original survives verbatim below as a corollary. *)
Theorem antispoof_general_any_env : forall e p,
  field_value Fobrname e p = ifreg "br.20" ->
  (* the frame carries IPv4 — discharges the `ether type ip` dependency guard the
     frontend (faithfully to nft) inserts before reading `ip daddr` on bridge *)
  field_value FMetaProtocol e p = [8; 0] ->
  read_payload_ok PNetwork 16 4 p = true ->     (* the ip daddr load succeeds *)
  concat_set_mem [field_value FIp4Daddr e p] (e_set e "vmaddrs") = true ->
  (* the (daddr . oifname) pair is NOT in vmantispoof — stated with the faithful
     per-field (cross-product) membership the kernel actually uses, NOT the old
     flat lexicographic [set_mem] over the concatenation. *)
  concat_set_mem [field_value FIp4Daddr e p; field_value FMetaOifname e p]
          (e_set e "vmantispoof") = false ->
  eval_table vm_fuel vmfilter_chains vmfilter_output e p = Drop.
Proof.
  intros e p Hobr Hethip Hok Hin Hpair. unfold Fobrname in Hobr.
  unfold eval_table, vm_fuel, vmfilter_output. cbn [c_rules c_policy].
  erewrite erj_drop_first; [ reflexivity | | | reflexivity ].
  (* rule_loadable (the antispoof rule) e p = true: only the ip daddr payload load
     can break, discharged by [Hok]. *)
  - unfold rule_loadable, end_loadable, tail_loadable, terminal_loadable, vmap_loadable,
      body_item_loadable, match_loadable, fields_loadable, field_loadable, load_ok.
    cbn -[read_payload_ok]. rewrite Hok. reflexivity.
  (* rule_applies (the antispoof rule) e p = true.  [cbn -[field_value]]
     reduces forallb/body_matches/eval_matchcond but keeps [field_value]
     wrapped, so the field-value and env hypotheses can rewrite them. *)
  - unfold rule_applies, rule_applies_walk, eval_matchcond, match_loadable, eval_matchcond_body,
      fields_loadable, field_loadable, load_ok.
    cbn -[field_value read_payload_ok].
    rewrite ?Hok, Hobr, Hethip, ?app_nil_r, Hin, Hpair. vm_compute. reflexivity.
Qed.

(** The pre-M4 statement, verbatim: the same property with the (inert)
    whole-env pin — a direct corollary of [antispoof_general_any_env].  Kept
    because it is README-claimed and gate-listed under this name; new work
    should cite [antispoof_general_any_env]. *)
Theorem antispoof_general : forall e p,
  e = gen_env ->
  field_value Fobrname e p = ifreg "br.20" ->
  field_value FMetaProtocol e p = [8; 0] ->
  read_payload_ok PNetwork 16 4 p = true ->
  concat_set_mem [field_value FIp4Daddr e p] (e_set e "vmaddrs") = true ->
  concat_set_mem [field_value FIp4Daddr e p; field_value FMetaOifname e p]
          (e_set e "vmantispoof") = false ->
  eval_table vm_fuel vmfilter_chains vmfilter_output e p = Drop.
Proof.
  intros e p _ Hobr Hethip Hok Hin Hpair.
  exact (antispoof_general_any_env e p Hobr Hethip Hok Hin Hpair).
Qed.

(** Axiom-freedom print (INFORMATIONAL: it goes to the `make proofs` build log
    but cannot fail the build).  The build-FAILING check is `make axioms`,
    whose AXIOM_GATE_THEOREMS list includes [antispoof_general_any_env],
    [antispoof_general] and the three concrete corollaries below — anything
    but "Closed under the global context" fails that target. *)
Print Assumptions antispoof_general_any_env.
Print Assumptions antispoof_general.

(** ** Concrete witness 1 — the spoofing attempt is blocked.

    In the three concrete corollaries the [e = gen_env] pin is a WITNESSING
    instantiation, not a hypothesis to relax: it supplies the parser's own set
    contents so the memberships compute, and — unlike the pre-M4 general form
    or Optiplex_Mark — no env-reading field hypothesis coexists with it, so
    the hypotheses are jointly satisfiable (the frames below are real).

    The container behind `inc-vikun` (vikunja, real address .14) sends a frame to
    budget's address 192.168.51.20.  The pair (192.168.51.20 . inc-vikun) is NOT
    in vmantispoof, so the frame is dropped: vikunja cannot impersonate budget. *)
Theorem vikunja_cannot_spoof_budget : forall e p,
  e = gen_env ->
  field_value Fobrname e p = ifreg "br.20" ->
  field_value FMetaProtocol e p = [8; 0] ->              (* an IPv4 frame *)
  read_payload_ok PNetwork 16 4 p = true ->            (* a well-formed IPv4 header *)
  field_value FIp4Daddr e p = ip4 192 168 51 20 ->      (* budget's address *)
  field_value FMetaOifname e p = ifreg "inc-vikun" ->   (* vikunja's interface *)
  eval_table vm_fuel vmfilter_chains vmfilter_output e p = Drop.
Proof.
  intros e p Henv Hobr Hethip Hok Hdaddr Hoif; subst e.
  apply antispoof_general; auto.
  - rewrite Hdaddr. vm_compute. reflexivity.
  - rewrite Hdaddr, Hoif. vm_compute. reflexivity.
Qed.

(** A second spoof: gentoo (behind vb-gentoo) trying to take hass's .10. *)
Theorem gentoo_cannot_spoof_hass : forall e p,
  e = gen_env ->
  field_value Fobrname e p = ifreg "br.20" ->
  field_value FMetaProtocol e p = [8; 0] ->              (* an IPv4 frame *)
  read_payload_ok PNetwork 16 4 p = true ->
  field_value FIp4Daddr e p = ip4 192 168 51 10 ->       (* hass's address *)
  field_value FMetaOifname e p = ifreg "vb-gentoo" ->    (* gentoo's interface *)
  eval_table vm_fuel vmfilter_chains vmfilter_output e p = Drop.
Proof.
  intros e p Henv Hobr Hethip Hok Hdaddr Hoif; subst e.
  apply antispoof_general; auto.
  - rewrite Hdaddr. vm_compute. reflexivity.
  - rewrite Hdaddr, Hoif. vm_compute. reflexivity.
Qed.

(** ** Concrete witness 2 — legitimate traffic is allowed.

    Budget's own frame (to .20, leaving its bound interface inc-budge) is NOT
    dropped: the (.20 . inc-budge) pair IS in vmantispoof, so the negated match
    fails, the rule does not fire, and the frame falls through to `policy accept`.
    The rule blocks *only* spoofing, not the legitimate binding. *)
Theorem budget_legitimate_allowed : forall e p,
  e = gen_env ->
  field_value Fobrname e p = ifreg "br.20" ->
  field_value FMetaProtocol e p = [8; 0] ->              (* an IPv4 frame *)
  read_payload_ok PNetwork 16 4 p = true ->
  field_value FIp4Daddr e p = ip4 192 168 51 20 ->
  field_value FMetaOifname e p = ifreg "inc-budge" ->    (* its OWN interface *)
  eval_table vm_fuel vmfilter_chains vmfilter_output e p = Accept.
Proof.
  intros e p Henv Hobr Hethip Hok Hdaddr Hoif. unfold Fobrname in Hobr.
  unfold eval_table, vm_fuel, vmfilter_output. cbn [c_rules c_policy].
  (* antispoof rule does not apply: the pair IS bound, so the `!=` match is false *)
  erewrite erj_skip.
  2:{ unfold rule_applies, rule_applies_walk, eval_matchcond, match_loadable, eval_matchcond_body,
        fields_loadable, field_loadable, load_ok.
      cbn -[field_value read_payload_ok].
      rewrite ?Hok, Hobr, Hethip, ?app_nil_r, Hdaddr, Hoif, ?Henv. vm_compute. reflexivity. }
  (* hass rule does not apply either: obrname is br.20, not br.1 *)
  erewrite erj_skip.
  2:{ unfold rule_applies, rule_applies_walk, eval_matchcond, match_loadable, eval_matchcond_body,
        fields_loadable, field_loadable, load_ok.
      cbn -[field_value read_payload_ok]. rewrite ?Hok, Hobr.
      vm_compute. reflexivity. }
  reflexivity.
Qed.

(** Every theorem above is about [eval_table], the specification; via
    [compile_table_correct] (Correct.v) the same verdict holds of the compiled
    netlink bytecode, exactly as Example_Ruleset.v shows for smtp_dropped. *)

(** Informational prints for the concrete corollaries (the build-failing check
    is `make axioms`, which gates all four theorems in this file). *)
Print Assumptions vikunja_cannot_spoof_budget.
Print Assumptions gentoo_cannot_spoof_hass.
Print Assumptions budget_legitimate_allowed.

(* ================================================================== *)
(** ** Projection license (U1): the parsed vmfilter table is write-free, so
    every [eval_table] statement in this file is a statement about the
    UNIFIED semantics ([Semantics.eval_table_u_writefree] /
    [Nft_Tactics.nft_yields_unified]). *)
Example vmfilter_output_license :
  forallb rule_writefree (c_rules vmfilter_output) = true
  /\ chains_writefree vmfilter_chains = true.
Proof. vm_compute. split; reflexivity. Qed.
