#!/usr/bin/env bash
# Download, configure, and build an upstream Linux kernel for the dev VM.
#
#   ./kernel/build.sh                # latest stable from kernel.org
#   KVER=6.18.35 ./kernel/build.sh   # pin a specific version (e.g. an LTS)
#   ./kernel/build.sh 6.18.35        # same, as a positional arg
#
# What it does:
#   1. Resolve the kernel version (arg / $KVER / kernel.org's latest_stable).
#   2. Download + extract the tarball into kernel/src/linux-<ver>/ (cached).
#   3. Configure: defconfig + kvm_guest.config + config.fragment, olddefconfig.
#   4. Build bzImage + modules with all cores.
#   5. Stage the kernel + modules into vm/mkosi.extra/ so `mkosi build` bakes a
#      UKI from them (see vm/mkosi.conf).
#   6. Write kernel/build.env (KERNEL_SRC / KERNEL_RELEASE / BZIMAGE) for the
#      Makefile, the module build, and vm scripts to source.
#
# Re-running is incremental: an existing source tree is reused and only changed
# objects rebuild. Change the version to fetch a different tree.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$HERE/.." && pwd)"
SRC_ROOT="$HERE/src"
STAGE="$REPO/vm/mkosi.extra"          # mkosi copies this verbatim into the image
JOBS="${JOBS:-$(nproc)}"

# --- 1. Resolve version -----------------------------------------------------
KVER="${1:-${KVER:-}}"
if [ -z "$KVER" ]; then
    echo ">> Querying kernel.org for the latest stable release..."
    KVER="$(curl -fsSL https://www.kernel.org/releases.json \
        | python3 -c 'import json,sys; print(json.load(sys.stdin)["latest_stable"]["version"])')"
fi
echo ">> Kernel version: $KVER"

MAJ="${KVER%%.*}"
TARBALL="linux-$KVER.tar.xz"
URL="https://cdn.kernel.org/pub/linux/kernel/v${MAJ}.x/$TARBALL"
SRC="$SRC_ROOT/linux-$KVER"

# --- 2. Download + extract --------------------------------------------------
mkdir -p "$SRC_ROOT"
if [ ! -d "$SRC" ]; then
    if [ ! -f "$SRC_ROOT/$TARBALL" ]; then
        echo ">> Downloading $URL"
        curl -fSL --progress-bar -o "$SRC_ROOT/$TARBALL.part" "$URL"
        mv "$SRC_ROOT/$TARBALL.part" "$SRC_ROOT/$TARBALL"
    fi
    # Optional integrity check against kernel.org's published sha256sums.
    if command -v sha256sum >/dev/null 2>&1; then
        echo ">> Verifying sha256..."
        WANT="$(curl -fsSL "https://cdn.kernel.org/pub/linux/kernel/v${MAJ}.x/sha256sums.asc" 2>/dev/null \
                | awk -v f="$TARBALL" '$2==f{print $1}' || true)"
        if [ -n "$WANT" ]; then
            GOT="$(sha256sum "$SRC_ROOT/$TARBALL" | awk '{print $1}')"
            [ "$WANT" = "$GOT" ] || { echo "!! sha256 mismatch ($GOT != $WANT)"; exit 1; }
            echo "   ok ($GOT)"
        else
            echo "   (no published checksum found; skipping — verify the PGP signature manually for production use)"
        fi
    fi
    echo ">> Extracting $TARBALL"
    tar -C "$SRC_ROOT" -xf "$SRC_ROOT/$TARBALL"
fi

# --- 3. Configure -----------------------------------------------------------
cd "$SRC"
if [ ! -f .config ]; then
    echo ">> Generating base config (defconfig + kvm_guest.config)"
    make -j"$JOBS" defconfig
    # kvm_guest.config turns on the common virtio/guest drivers as built-ins.
    make -j"$JOBS" kvm_guest.config 2>/dev/null || echo "   (kvm_guest.config unavailable on this version; fragment covers it)"
fi
echo ">> Merging config.fragment"
./scripts/kconfig/merge_config.sh -m .config "$HERE/config.fragment" >/dev/null
make -j"$JOBS" olddefconfig

# --- 4. Build ---------------------------------------------------------------
echo ">> Building bzImage + modules with $JOBS jobs (this takes a while)..."
make -j"$JOBS" bzImage modules

RELEASE="$(make -s kernelrelease)"
BZIMAGE="$SRC/arch/x86/boot/bzImage"
echo ">> Built kernel release: $RELEASE"

# --- 5. Stage kernel + modules into the image tree --------------------------
echo ">> Staging kernel + modules into $STAGE/usr/lib/modules/$RELEASE"
MODDIR="$STAGE/usr/lib/modules/$RELEASE"
rm -rf "$STAGE/usr/lib/modules"
mkdir -p "$STAGE/usr/lib/modules"
# INSTALL_MOD_PATH=$STAGE/usr  ->  modules land in $STAGE/usr/lib/modules/<rel>
make -s modules_install INSTALL_MOD_PATH="$STAGE/usr" >/dev/null
# Drop the dangling build/source symlinks modules_install leaves (they point at
# the host source tree and confuse mkosi's image-copy).
rm -f "$MODDIR/build" "$MODDIR/source"
# mkosi/ukify builds the UKI from this vmlinuz.
cp -f "$BZIMAGE" "$MODDIR/vmlinuz"

# --- 6. Record where everything is -----------------------------------------
cat > "$HERE/build.env" <<EOF
# Generated by kernel/build.sh — sourced by the Makefile, module build, vm scripts.
KERNEL_VERSION=$KVER
KERNEL_RELEASE=$RELEASE
KERNEL_SRC=$SRC
BZIMAGE=$BZIMAGE
EOF

echo
echo ">> Done."
echo "   release : $RELEASE"
echo "   source  : $SRC"
echo "   bzImage : $BZIMAGE"
echo "   staged  : $MODDIR  (vmlinuz + modules for the image)"
echo
echo "   Next:  make image   # bake the VM image (UKI from this kernel)"
echo "          make vm      # boot it"
