(** * Main: the entry-point theorems of the development.

    ONE theorem per verified axis, restated verbatim from its home file, so an
    external reviewer can answer "what exactly is proved, under which
    evaluator, and is it axiom-free?" from this file alone.  Each restatement
    is a definitional alias ([exact] of the original — no new proof term) and
    is followed by [Print Assumptions], so the build log carries an
    axiom-freedom verdict for every entry point; `make axioms` re-checks the
    same set from the compiled .vo files and fails on anything but "Closed
    under the global context".

    The classification of EVERY other Theorem/Corollary (HEADLINE / STAGE /
    SUPPORTING / SUPERSEDED / DEMO, with derivation edges) and the evaluator
    feature matrix live in [proof/THEOREMS.md]. *)

From Stdlib Require Import List.
From Nft Require Import Bytes Packet Verdict Syntax Bytecode Semantics Compile
  Correct Optimize Optimize_Table Optimize_Uncond.

(** ** Axis 1 — the compiler, at ruleset/hook level ([compile_hook_correct]).

    For every fuel, every registered ruleset [rs], every netfilter hook [h] and
    every packet [p]: selecting and priority-ordering the base chains for [h],
    compiling each (with its jump-target chain environment), and running the
    netfilter dispatch over the compiled bases yields exactly the verdict of
    the DSL dispatch [eval_hook].  This is the top of the jump-aware,
    mutation-free strand: it covers jump/goto/return, user chains, multi-table
    and hook/priority dispatch, and quantifies over the whole environment
    (sets/maps/conntrack/routes), but threads no writes between rules
    (mutation x jump/goto is not jointly verified — see THEOREMS.md). *)
Theorem main_compile_hook_correct : forall fuel rs h p,
  run_ruleset fuel (map compile_base (select_hook rs h)) p = eval_hook fuel rs h p.
Proof. exact compile_hook_correct. Qed.
Print Assumptions main_compile_hook_correct.

(** ** Axis 1, sequence form ([compile_seq_correct]) — a congruence corollary.

    Lifting axis 1 over a packet sequence whose shared environment is updated
    between packets by an ARBITRARY, caller-supplied
    [step : verdict -> env -> env].  Because [step] is unconstrained, this is a
    per-packet congruence lifted over a sequence — it does NOT assert that the
    ruleset's own state accumulation is preserved (that is axis 2 below, where
    the env evolution is generated by the ruleset itself). *)
Theorem main_compile_seq_correct : forall fuel rs h step e packets,
  seq_eval (fun e' p => run_ruleset fuel (map compile_base (select_hook rs h)) (set_env p e'))
           step e packets
  = seq_eval (fun e' p => eval_hook fuel rs h (set_env p e')) step e packets.
Proof. exact compile_seq_correct. Qed.
Print Assumptions main_compile_seq_correct.

(** ** Axis 2 — mutation and cross-packet learning ([compile_seq_mut_correct]).

    For a single chain [c] whose rules are well-formed ([mut_wf] — a
    non-degeneracy condition every real ruleset satisfies, not a feature
    scope): running a packet sequence with the compiled bytecode, threading the
    environment each traversal LEAVES (meta/ct writes, dynset-learned set/map
    elements) into the next packet, reproduces the DSL sequence verdict-for-
    verdict.  Here — unlike axis 1's sequence form — the env evolution is
    generated by the ruleset itself, so an `add @s {…}` on an earlier packet
    provably reaches a `lookup @s` on a later one.  This strand covers
    mutation but not jump/goto (single chain, no chain environment). *)
Theorem main_compile_seq_mut_correct : forall c e packets,
  forallb mut_wf (c_rules c) = true ->
  seq_eval_env (fun e' p => run_chain_mut_env (compile_chain c) (c_policy c) (set_env p e')) e packets
  = seq_eval_env (fun e' p => eval_chain_mut_env c (set_env p e')) e packets.
Proof. exact compile_seq_mut_correct. Qed.
Print Assumptions main_compile_seq_mut_correct.

(** ** Axis 3 — the optimizer pipeline, end-to-end to the bytecode
    ([optimize_table_uncond_compile_correct]).

    For every input chain [c] — NO cleanliness or freshness precondition —
    running the shipped 18-stage `nft -o` consolidation pipeline
    ([optimize_table_uncond], the term the CLI executes), then compiling the
    optimised chain and running the VM against the synthesised set/map
    declarations, yields exactly the DSL verdict of the ORIGINAL chain, for
    every packet and every base environment.  Scope: PER CHAIN — the optimizer
    is quantified over a single chain and all environments/packets;
    multi-chain/hook preservation is axis 1's separate family, not composed
    with the optimizer. *)
Theorem main_optimize_table_uncond_compile_correct : forall c base p n' d' c',
  optimize_table_uncond c = (n', d', c') ->
  run_chain (compile_chain c') (c_policy c') (set_env p (env_with_sets base d'))
  = eval_chain c (set_env p (env_with_sets base empty_decls)).
Proof. exact optimize_table_uncond_compile_correct. Qed.
Print Assumptions main_optimize_table_uncond_compile_correct.
